package pl.put.poznan.transformer.logic;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Connection is a class representing one directed Connection between two nodes of the network. Each Connection also has set value.
 * Most object of this class are generated by mapping json gotten as the input.
 * @author      Artur Mostowski
 * @author      Dominik Szmyt
 * @author      Łukasz Grygier
 * @author      Jakub Wąsik
 * @since       1.0
 */
public class Connection {
    @JsonProperty("from")
    private int from;
    @JsonProperty("to")
    private int to;
    @JsonProperty("value")
    private Double value;


    public Connection() {
    }

    /**
     * Class constructor
     * @param from       ID of the node from which connection originates
     * @param to         ID of the node that the connection heads towards
     * @param value      Value of the connection whether it be cost, throughput, or capacity
     * @since           1.0
     */
    public Connection(int from, int to, Double value) {
        this.from = from;
        this.to = to;
        this.value = value;
    }

    public int getFrom() {
        return from;
    }

    public int getTo() {
        return to;
    }

    public Double getValue() {
        return value;
    }
}
